== Beef Stroganoff

=== Ingredients

* 1 pound wide egg noodles
* 4 tablespoons (1/4 cup) butter, divided
* 1 1/2 pounds thinly-sliced steak (I used flank steak)
* 1 small white onion, thinly sliced
* 4 cloves garlic, minced
* 1 pound sliced mushrooms (I used a mix of button and baby bella mushrooms)
* 1/2 cup dry white wine (or you can substitute in more beef broth)
* 1 1/2 cups beef broth
* 1 tablespoon Worcestershire sauce
* 3 tablespoons flour
* 1/2 cup sour cream
* optional garnishes: chopped fresh parsley, extra black pepper

=== Directions

. Cook noodles according to package directions 
. Melt 2 tablespoons butter in a large saute pan over medium-high heat.
. Add the steak in a single layer, seasoned with a few generous pinches of salt, and let it cook undisturbed for about 3 minutes to get a good sear.
. Flip the steak, and cook on the other side until browned, about another 3 minutes.
. Then remove steak from pan with a slotted spoon, and transfer to a separate plate. Set aside.
    .. If your pan is not big enough to fit all of the steak in a single layer, then add just 1 tablespoon of butter to the pan and cook half of the steak.
    .. Then repeat with a second batch.
. Return pan to heat and add the remaining 2 tablespoons butter.
. Once it has melted, add the onions and saute for about 3 minutes.
. Add garlic and mushrooms, and stir to combine.
. Continue sauteing for an additional 5-7 minutes, or until the mushrooms are cooked and the onions are soft.
. Add the white wine, and deglaze the pan by using your cooking spoon to scrape the brown bits off the bottom of the pan.
. Let the mixture cook down for an additional 3 minutes.
. Meanwhile, in a separate bowl, whisk together the beef broth, worcestershire sauce and flour until smooth.
. Pour the beef broth mixture into the pan, and stir to combine.
. Let the mixture simmer for 5 minutes, stirring occasionally.
. Then stir in sour cream until combined, and then stir the cooked steak back in.
. Season with additional salt if needed.
. Serve over the egg noodles, garnished with parsley if desired.

link:index.html[Index]
