== Chicken Fried Rice

=== Ingredients

* 3 large eggs
* Kosher salt
* Vegetable oil, for frying
* 4 boneless, skinless chicken breast halves, cut into thin strips
* 1 teaspoon sesame oil
* 1 large onion, finely chopped
* 2 garlic cloves, finely minced
* 4 cups cold, cooked rice
* 6 green (spring) onions, thinly sliced, plus more for garnish, optional
* 2 tablespoons soy sauce

=== Directions

. Beat eggs with a whisk in a small bowl and season with salt, to taste.
. Heat very little oil in a medium frying pan over medium heat and make an omelette using half the beaten eggs.
. Turn out onto a plate to cool (do not fold omelette).
. Repeat process with remaining beaten eggs.
. Place 1 omelette on top of the other, fold, coarsely chop and set aside.
. In a medium bowl, toss chicken strips with the sesame oil and season with salt, to taste.
. Heat 3 tablespoons vegetable oil over high heat in large frying pan or wok and stir-fry the prepared chicken strips until lightly golden, about 2 to 3 minutes.
. Add the onion and garlic and stir-fry for 1 to 2 minutes or until onion has softened.
. Add 2 tablespoons more vegetable oil and when hot, stir in the cooked rice and green onions, tossing and mixing thoroughly until very hot.
. Sprinkle with soy sauce and mix evenly.
. Remove from heat and stir in chopped cooked egg.
. If desired, garnish with additional sliced green onions.

link:index.html[Index]