== Orange Chicken Fingers

=== For Chicken Fingers

* Cooking spray
* 1 tablespoon sesame seeds
* 4 cups (3 & 1/2 ounces) crispy rice cereal
* 1/2 teaspoon grated orange zest
* Kosher salt and freshly ground black pepper
* 2 egg whites
* 1 tablespoon low-sodium teriyaki sauce
* 1 & 1/2 pounds boneless skinless chicken breast, cut into tenders 4 by 1 1/2-inches, about 18 pieces

=== For the sauce

* 1/2 cup low-sugar orange marmalade
* 1 tablespoon low-sodium teriyaki sauce
* 1 teaspoon grated ginger
* 1 tablespoon freshly squeezed lemon juice

=== Directions

. Preheat the oven to 425 degrees F. Place a wire rack on a baking sheet and lightly mist with nonstick cooking spray.
. Put the sesame seeds in a small nonstick skillet set over medium heat. Cook, stirring often, until golden brown and fragrant, about 5 minutes.
. Set aside to cool.
. Put the cereal in a plastic storage bag and crush with a rolling pin or heavy can until coarsely crushed.
. In a shallow bowl combine the toasted sesame seeds, crushed cereal and orange zest and lightly season with salt and pepper.
. In a second shallow dish, beat the egg whites with the teriyaki sauce.
. Dip each chicken tender in the egg mixture and then the cereal mixture, pressing to coat well.
. Place on the rack and mist the chicken with nonstick cooking spray.
. Bake until the crust is golden and the chicken is cooked through, 18 to 20 minutes.
. Meanwhile, in a small sauce pot heat the marmalade, teriyaki and ginger over medium heat until melted and well combined.
. Remove from heat and stir in the lemon juice.

link:index.html[Index]