== Roasted Rosemary Chicken with Potatoes

=== Ingredients

* 1 & 1/2 pounds small baby red or tricolor creamer potatoes, quartered
* 1 tablespoon extra-virgin olive oil
* 1 & 1/2 teaspoons finely chopped fresh rosemary
* Kosher salt
* Four 6- to 8-ounce halved bone-in chicken breasts with skin

=== Directions

. Position an oven rack in the top of the oven and preheat to 450F.
. Line the bottom of a roasting pan with parchment paper.
. Put the potatoes in a large bowl, sprinkle with 2 teaspoons of the oil, the rosemary and 1/4 teaspoon salt and toss to combine.
. Arrange the potatoes in a single layer in the pan and roast until the potatoes just begin to soften slightly, stirring as needed, 25 to 30 minutes.
. Meanwhile, sprinkle the chicken breasts with 1/2 teaspoon salt.
. Heat the remaining 1 teaspoon of oil in a large nonstick skillet over medium-high heat.
. Cook the chicken skin-side down until just golden, 4 to 5 minutes.
. Set the chicken skin-side up on the partially roasted potatoes.
. Roast until an instant-read thermometer inserted in the thickest part of the meat reaches 160F and the juices run clear, 25 to 30 minutes.
. Transfer the chicken and potatoes to a platter and serve.

link:index.html[Index]