== Daniel’s Bread

=== Ingredients

* 1 Tablespoon bread machine (instant) yeast *
* 2 3/4 cups warm water (110° to 115°)
* 3 Tablespoons sugar
* 1 Tablespoon salt
* 2 Tablespoons olive oil
* 6 Cups all-purpose flour
* 1/3 Cup ground flax seed
* 1/3 Cup hulled hep seeds
* 1/3 Cup chia seed

=== Directions

. Mix ingredients. I just dump them all in the mixer and set it to stir.
. Continue to stir until the ingredients mix into a firm dough. The dough should be slightly sticky but pull into a ball preferring to stick to itself than the bowl.
. Knead the dough. I just leave the dough stirring until its ready.
   .. To test of your dough is done kneading remove a small portion, flatten it, hold it up to a light and stretch in all four directions at the same time. If the dough stretches into spiderweb like lines its ready, if not keep kneading.
. Leave the dough to rise for one hour.
   .. If the dough has not doubled in size, place it in a warmer environment and give it another 30 minutes.
   .. I like to warm the oven up to 100 degrees and let the dough rise there.
. Punch the dough down.
. Divide it in half.
. Place in pre greased bread pans.
   .. I have an oil sprayer I fill with olive oil.
. Leave the dough to rise for one hour.
   .. See the notes on step 4, repeat them.
. Bake at 375° for 30-35 minutes.
. While its cooling rub the top of the loaf with butter and cool in the pan.
    . I only use real butter, not margarine.

+*+ one package of yeast is 1/4 ounce or 2 1/4 teaspoons, but I use a tablespoon because I don't want to dirty more dishes and the result is the same.

link:index.html[Index]