== Chocolate Mousse

=== Ingredients

* 3 ounces semisweet chocolate, chopped
* 3 ounces bittersweet chocolate, chopped
* 3 tablespoons unsalted butter
* 3 tablespoons strong coffee, cooled
* 1 1/2 teaspoons unflavored gelatin
* 3 eggs, separated
* 3 tablespoons confectioners' sugar
* 1/4 teaspoon cream of tartar
* 1/4 cup granulated sugar
* 1/2 cup heavy cream

=== Directions

. Combine chocolates, and butter in a medium bowl set over barely simmering water.
. Stir frequently until chocolate is just melted.
. Set aside to cool to lukewarm.
. Place coffee in a small bowl and add gelatin. 
. Set aside until gelatin has softened, about 5 minutes.
. In a medium heatproof bowl, whisk egg yolks until smooth.
. Place bowl over the pot of simmering water and whisk in coffee-gelatin mixture and confectioners' sugar.
. Continue to whisk constantly until mixture is thickened, light, and fluffy, about 4 minutes.
. Remove from heat and whisk mixture into melted chocolate.
. Set aside until cooled to room temperature.
. In a separate large bowl, whip egg whites until foamy.
. Add cream of tartar and, little by little, gradually beat in granulated sugar.
. Increase speed to high and beat until stiff peaks form.
. Fold about 1/4 of egg whites into chocolate mixture to lighten it, then gently fold in the remaining beaten whites.
. In a large bowl, whip heavy cream to just beyond soft peaks but not quite stiff.
. Gently but thoroughly fold whipped cream into chocolate mixture.
. Transfer mousse to refrigerator until moderately set up, at least 2 hours and up to overnight.

=== Notes

*  Can be used as a filling for cakes or piped into small dessert dishes and serve on its own.
