== Cinnamon Roll Pie Crust

=== Ingredients

* 1 Pie crust
* 4 Tablespoons butter, melted
* 1/2 cup brown sugar
* 2 Teaspoons cinnamon
* 1/2 teaspoon pure vanilla extract

=== Directions

. On a lightly floured surface, roll out the pie crust a few times to even it out to about 1/2 inch thickness.
. In a small bowl, mix the butter with the sugar, cinnamon and vanilla extract to combine.
. Spoon the mixture into the center of the crust.
. Use a spatula to spread it evenly over the entire crust.
. Starting with the side closest to you, roll the crust into a tight spiral.
. Cut the finished spiral into 1/2 inch-thick pieces.
. On a lightly floured surface, use a rolling pin to roll each piece into a 1/4 inch-thick round. Place the pieces in a pie plate, overlapping them slightly and pressing to seal. 
. If the pieces aren’t sticking together well, use a little water to help “glue” them.
. Continue placing rounds of dough in the pie plate until the entire plate is full; trim any excess hanging over the edge.
. Use the tines of a fork to press indentations all around the edge.
. Chill the crust well before filling and baking, and bake according to your preferred pie recipe.

link:index.html[Index]