== Double Chocolate Meringue Kisses

=== Ingredients

* 3 egg whites
* 1 cup granulated sugar
* 1/4 teaspoon cream of tartar
* pinch of salt
* 1 teaspoon vanilla extract
* 1/4 cup cocoa powder
* 2 tablespoons finely chopped white or dark chocolate

=== Directions

. Preheat the oven to 225ยบ F.
. In a medium heat-proof bowl or the bowl of the standing mixer, combine egg whites, sugar, cream of tartar and salt.
. Set the bowl over a pot of barely simmering water and cook, whisking constantly, until mixture is warm and frothy and sugar is dissolved, about 2 minutes.
. Remove the bowl from the heat and using an electric mixer, beat the mixture on high until the egg whites are glossy and stiff, about 3 minutes.
. Beat in the vanilla.
. Fold in the cocoa powder and then the chopped chocolate.
. Transfer the mixture to a medium size piping bag and pipe 30 kisses on a parchment-lined baking sheet.
. Bake until the meringues are dry to the touch but still slightly soft in the center, about 40 minutes.
. Let cool completely before removing from the parchment paper.

=== Notes

* Dots
