== Espresso-Chocolate Meringue Kisses

=== Ingredients

* 2 large egg whites, at room temperature
* 1/4 teaspoon cream of tartar
* 2/3 cup superfine sugar
* 1/3 cup finely chopped bittersweet or semisweet chocolate
* pinch of salt
* 2 teaspoons unsweetened cocoa powder
* 1 1/2 teaspoons instant espresso powder

=== Directions

. Preheat the oven to 225°F and line two baking sheets with parchment paper.
. In a medium mixing bowl, beat the egg whites and the cream of tartar using an electric mixer on low speed until foamy.
. Increase the speed to medium and begin adding the sugar, a tablespoon at a time, and beat until the meringue forms stiff and glossy peaks.
. Fold in the chocolate and salt, and then sift the cocoa and espresso powder over the meringue.
. Using a large rubber spatula, fold the mixture onto itself several times to incorporate the powders.
. Spoon the meringue into a pastry bag fitted with a large plain tip, and pipe the mixture onto the lined baking sheets, forming 1-inch size kisses and staggering rows of the kisses about 1 1/2 inches apart.
. Bake in the center of the oven until the kisses are crisp on the outside and yet still slightly chewy inside, about 45 minutes.
. Remove from the oven and set aside until completely cool.
. Serve or store in an airtight container for up to 1 week.
